# Generated by Django 5.2.4 on 2025-07-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('doctor', 'Doctor'), ('patient', 'Patient')], default='patient', max_length=10),
        ),
    ]
