# Generated by Django 5.2.4 on 2025-08-03 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='birthday',
        ),
    ]
