# Generated by Django 5.2.4 on 2025-08-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_patientprofile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('doctor', 'Doctor'), ('patient', 'Patient'), ('cashier', 'Cashier')], default='patient', max_length=20),
        ),
    ]
