# Generated by Django 5.2.4 on 2025-08-10 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='amount',
        ),
    ]
