# Generated by Django 5.2.4 on 2025-08-10 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_appointment_service_remove_invoice_amount'),
        ('service', '0002_room_service_doctors_service_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='service.room', verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(to='service.service', verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Итоговая сумма'),
        ),
    ]
