# Generated by Django 5.2.4 on 2025-08-13 11:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_appointment_room_appointment_services_and_more'),
        ('service', '0002_room_service_doctors_service_rooms'),
        ('users', '0005_remove_patientprofile_birthday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='room',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='services',
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата/время приема'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланирован'), ('ready', 'Готов к приему'), ('done', 'Завершен'), ('canceled', 'Отменен')], default='planned', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='AppointmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.appointment', verbose_name='Прием')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.doctorprofile', verbose_name='Врач')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.room', verbose_name='Кабинет')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.service', verbose_name='Услуга')),
            ],
        ),
    ]
