# Generated by Django 5.2.4 on 2025-08-13 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_appointment_options_remove_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentitem',
            name='room',
        ),
    ]
