# Generated by Django 5.2.4 on 2025-08-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_remove_invoice_appointment_remove_invoice_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Счёт', 'verbose_name_plural': 'Счета'},
        ),
    ]
