# Generated by Django 5.2.4 on 2025-08-21 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_invoice_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='service_entry',
        ),
        migrations.AddField(
            model_name='invoice',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_link', to='finance.appointment'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
