# Generated by Django 5.2.4 on 2025-08-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('users', '0005_remove_patientprofile_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название кабинета')),
                ('room_type', models.CharField(blank=True, max_length=100, verbose_name='Тип кабинета')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='doctors',
            field=models.ManyToManyField(related_name='services', to='users.doctorprofile', verbose_name='Врачи'),
        ),
        migrations.AddField(
            model_name='service',
            name='rooms',
            field=models.ManyToManyField(related_name='services', to='service.room', verbose_name='Кабинеты'),
        ),
    ]
