# Generated by Django 5.2.4 on 2025-08-13 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_appointmentitem_room'),
        ('service', '0002_room_service_doctors_service_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='rooms',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
